name: Apply Patch to shopify-dev
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Commit message"
        required: true
      files_b64:
        description: "Base64 of JSON: [{ \"path\": \"...\", \"content_b64\": \"...\" }, ...]"
        required: true

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shopify-dev
        uses: actions/checkout@v4
        with:
          ref: shopify-dev

      - name: Decode files payload
        run: |
          echo '${{ inputs.files_b64 }}' | base64 -d > /tmp/files.json
          cat /tmp/files.json

      - name: Write files to repo
        run: |
          node - <<'NODE'
          const fs = require('fs'), path = require('path');
          const files = JSON.parse(fs.readFileSync('/tmp/files.json','utf8'));
          for (const f of files) {
            const p = f.path;
            const dir = path.dirname(p);
            const raw = Buffer.from(f.content_b64, 'base64').toString('utf8');
            fs.mkdirSync(dir, { recursive: true });
            fs.writeFileSync(p, raw, 'utf8');
            console.log('Wrote', p);
          }
          NODE

      - name: Commit
        run: |
          git config user.name  "jmee09-bot"
          git config user.email "bot@example.com"
          git add -A
          git commit -m "${{ inputs.message }}" || echo "No changes"

      - name: Push
        run: git push origin HEAD:shopify-dev
